baseURL = "https://eist.radio/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']

# Use this to include raw HTML in posts
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[services]
  [services.rss]
    limit = 42

[languages]
  [languages.en]
    title = 'Éist'
    [languages.en.params]
      homeSubtitle = "Éist is a radio station"
    weight = 1

languageCode = "en-us"

rssLimit = 10

enableEmoji = true

[frontmatter]
date = ["lastmod", "date", "publishDate"]
lastmod = ["date", "lastmod", ":git", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[security]
  [security.funcs]
    getenv = ['^API_KEY$']

[params.author]
  name = "Éist"
  about = "about"

[params.meta]
  favicon = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Place custom js and css in static/js and static/css
  # custom_css = ["custom.css"]
  custom_js = ["js/player.js"]

  # Metadata mostly used in document's head
  description = "Éist is an internet radio station based in Cork, Ireland."
  themeColor = "#4733FF"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  pinned = "Pinned Posts"
  descriptionInPosts = true
  human = ["single","posts"]
  denyRobots = "noindex, nofollow, noarchive"
  allowRobots = "index, follow"
  siteNoIndex = false
  # noIndexPages = ["404 Page not found"]
  logo = "eist-logo-small.png"

  [[params.socialLinks]]
    name = "email"
    url = "mailto:info@eist.radio"

  [[params.socialLinks]]
    name = "discord"
    url = "https://discord.gg/WRFv7Wvb3P"

  [[params.socialLinks]]
    name = "instagram"
    url = "https://www.instagram.com/eistradio"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/eist-radio/eist"

[menu]

  [[menu.main]]
    name = "about"
    url = "about/"
    weight = 1

#   [[menu.main]]
#     name = "listen"
#     url = "/"
#     weight = 1

#   [[menu.main]]
#     name = "schedule"
#     url = "schedule/"
#     weight = 2

  [[menu.main]]
    name = "events"
    url = "events/"
    weight = 2

  [[menu.main]]
    name = "artists"
    url = "artists/"
    weight = 3

#   [[menu.main]]
#     name = "chat"
#     url = "chat/"
#     weight = 5

  [[menu.main]]
    name = "support us"
    url = "support/"
    weight = 4

  [[menu.main]]
    name = "get involved"
    url = "get-involved/"
    weight = 5